version: '3.8'

services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/data
    restart: unless-stopped

volumes:
  h2-data:
